#ifndef FAST_RAY_TRIANGLE_INTERSECTION_HPP
#define FAST_RAY_TRIANGLE_INTERSECTION_HPP

// Border types
#define BORDER_NORMAL 0
#define BORDER_INCLUSIVE 1
#define BORDER_EXCLUSIVE 2

// Line types
#define LINE_TYPE_RAY 0
#define LINE_TYPE_LINE 1
#define LINE_TYPE_SEGMENT 2

// Plane types
#define PLANE_TYPE_TWOSIDED 0
#define PLANE_TYPE_ONESIDED 1


#define COLUMNS_SIZE 3


#endif